# Generated by Django 4.2 on 2023-12-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='business_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='business_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
