# Generated by Django 4.2 on 2024-01-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
